name: CI

on:
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: echo Hello, world!

      - name: print branch name
        if: ${{ github.ref_name }} == 'dev'
        run: echo dev
