name: CI

on:
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set environment variables
        run: |
          if [ ${GITHUB_REF##*/} == "main" ]; then
            echo "ENV_COND=prod" >> $GITHUB_ENV
          else
            echo "ENV_COND=dev" >> $GITHUB_ENV
          fi
      - name: print branch name
        run: echo "${{ env.ENV_COND }}"
